import { Game, GameCategoryTab, PlayerScore } from "@/types/game-card";

export const GAMES: Game[] = [
  {
    id: "1",
    title: "香港",
    type: "hk",
    description: "隔天开奖的 6+1 游戏",
    thumbnail: "https://picsum.photos/200/300/?=1",
    rating: 4.8,
    region: "hk",
    category: "marksix",
    playersOnline: 1243,
    isFeatured: true,
    isNew: true,
  },
  {
    id: "2",
    title: "澳门",
    type: "mo",
    description: "每晚开奖的 6+1 游戏",
    thumbnail: "https://picsum.photos/200/300/?=2",
    rating: 4.5,
    region: "mo",
    category: "marksix",
    playersOnline: 892,
    isFeatured: true,
  },
  {
    id: "3",
    title: "新澳门",
    type: "newmo",
    description: "每晚开奖的 6+1 游戏",
    thumbnail: "https://picsum.photos/200/300/?=3",
    rating: 4.7,
    region: "mo",
    category: "marksix",
    playersOnline: 1500,
    isFeatured: true,
  },
  {
    id: "4",
    title: "台湾",
    type: "tw",
    description: "每晚开奖的 6+1 游戏",
    thumbnail: "https://picsum.photos/200/300/?=4",
    rating: 4.6,
    region: "tw",
    category: "marksix",
    playersOnline: 1000,
    isFeatured: true,
  },
  // {
  //   id: "5",
  //   title: "动作游戏",
  //   type: "jp",
  //   description: "控制角色，完成任务",
  //   thumbnail: "https://picsum.photos/200/300/?=5",
  //   rating: 4.9,
  //   region: "medium",
  //   category: "action",
  //   playersOnline: 1200,
  //   isFeatured: true,
  // },
  // {
  //   id: "6",
  //   title: "模拟经营",
  //   type: "us",
  //   description: "经营你的企业，收集资源",
  //   thumbnail: "https://picsum.photos/200/300/?=6",
  //   rating: 4.8,
  //   region: "medium",
  //   category: "action",
  //   playersOnline: 1100,
  //   isFeatured: true,
  // },
  // {
  //   id: "7",
  //   title: "角色扮演",
  //   type: "kr",
  //   description: "扮演角色，探索世界",
  //   thumbnail: "https://picsum.photos/200/300/?=7",
  //   rating: 4.7,
  //   region: "medium",
  //   category: "action",
  //   playersOnline: 1300,
  //   isFeatured: true,
  // },
  // 更多游戏数据...
];

export const CATEGORIES: GameCategoryTab[] = [
  { id: "1", name: "全部", icon: "apps", category: "all" },
  { id: "2", name: "六合", icon: "color-filter", category: "marksix" },
  { id: "3", name: "动作", icon: "game-controller", category: "action" },
  { id: "4", name: "策略", icon: "grid", category: "strategy" },
  { id: "5", name: "冒险", icon: "map", category: "adventure" },
  // { id: "6", name: "卡牌", icon: "layers", category: "card" },
  // { id: "7", name: "音乐", icon: "business", category: "music" },
  // { id: "8", name: "赛车", icon: "car-sport", category: "racing" },
  // { id: "9", name: "体育", icon: "school", category: "sports" },
  // { id: "10", name: "模拟", icon: "accessibility", category: "simulation" },
  // { id: "11", name: "文字", icon: "logo-wordpress", category: "word" },
  // { id: "12", name: "教育", icon: "school", category: "educational" },
  // { id: "13", name: "娱乐", icon: "balloon", category: "entertainment" },
  // { id: "14", name: "家庭", icon: "grid", category: "family" },
  // { id: "15", name: "街机", icon: "person-circle", category: "arcade" },
  // { id: "16", name: "棋牌", icon: "clipboard", category: "board" },
];

export const LEADERBOARD_DATA: PlayerScore[] = [
  {
    userId: "1",
    username: "游戏大师",
    avatar: "https://picsum.photos/200/300.jpg",
    score: 12500,
    rank: 1,
  },
  {
    userId: "2",
    username: "速通玩家",
    avatar: "https://picsum.photos/200/300.jpg",
    score: 11200,
    rank: 2,
  },
  {
    userId: "3",
    username: "新手玩家",
    avatar: "https://picsum.photos/200/300.jpg",
    score: 9800,
    rank: 3,
  },
  {
    userId: "4",
    username: "玩家4",
    avatar: "https://picsum.photos/200/300.jpg",
    score: 9000,
    rank: 4,
  },

  // 更多玩家数据...
];
